name: Docker PHP Images GitHub workflow

on:
  pull_request:
    branches:
      - 'v3'
  push:
    branches:
      - 'v3'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_test_maybe_release:
    strategy:
      matrix:
        include:
          - variant: 'cli'
            php_version: '7.4'
          - variant: 'apache'
            php_version: '7.4'
          - variant: 'fpm'
            php_version: '7.4'
          - variant: 'cli'
            php_version: '7.3'
          - variant: 'apache'
            php_version: '7.3'
          - variant: 'fpm'
            php_version: '7.3'
          - variant: 'cli'
            php_version: '7.2'
          - variant: 'apache'
            php_version: '7.2'
          - variant: 'fpm'
            php_version: '7.2'
          - variant: 'cli'
            php_version: '7.1'
          - variant: 'apache'
            php_version: '7.1'
          - variant: 'fpm'
            php_version: '7.1'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Build and test
        run: |
          PHP_VERSION="${{ matrix.php_version }}" BRANCH="v3" VARIANT="${{ matrix.variant }}" ./build-and-test.sh
          docker images | grep thecodingmachine/php
      - name: Login to DockerHub
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          BRANCH_VARIANT=`echo "${{ matrix.variant }}" | sed 's/\./-/g'`
          docker push thecodingmachine/php:${{ matrix.php_version }}-v3-slim-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${{ matrix.php_version }}-v3-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${{ matrix.php_version }}-v3-${BRANCH_VARIANT}-node8
          docker push thecodingmachine/php:${{ matrix.php_version }}-v3-${BRANCH_VARIANT}-node10
          docker push thecodingmachine/php:${{ matrix.php_version }}-v3-${BRANCH_VARIANT}-node12