name: Docker PHP Images GitHub workflow

on:
  pull_request:
    branches:
      - 'v4'
  push:
    branches:
      - 'v4'
  schedule:
    - cron: '42 3 * * 0'

jobs:
  build_test_maybe_release:
    strategy:
      matrix:
        php_version: ['8.1','8.0','7.4', '7.3','7.2']
        variant: ['apache','cli','fpm']
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout
        uses: actions/checkout@v1
#      - name: Build locally
#        run: |
#          PHP_VERSION="${{ matrix.php_version }}"
#          docker buildx bake --load \
#            --set "*.platform=linux/amd64" \
#            php${PHP_VERSION//.}-slim-${{ matrix.variant }}
#          docker buildx bake --load \
#            --set "*.platform=linux/amd64" \
#            php${PHP_VERSION//.}-${{ matrix.variant }}-all
#          PHP_VERSION_MINOR=`docker run --rm thecodingmachine/php:${PHP_VERSION}-v4-slim-cli php -v | head -n1 | grep -P '\d+\.\d+\.\d+' -o | head -n1`
#          echo "PHP_VERSION_MINOR=${PHP_VERSION_MINOR}" >> $GITHUB_ENV
#          echo "PHP Version : ${PHP_VERSION_MINOR}" >> $GITHUB_STEP_SUMMARY
#          docker images --filter=reference=thecodingmachine/php >> $GITHUB_STEP_SUMMARY
#      - name: Test ${{ matrix.variant }}
#        run:  |
#          PHP_VERSION="${{ matrix.php_version }}" BRANCH=v4 VARIANT=${{ matrix.variant }} ./test-image.sh
#          echo "${{ matrix.variant }} variant OK" >> $GITHUB_STEP_SUMMARY
      - name: Login to DockerHub
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to repository
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          PHP_VERSION="${{ matrix.php_version }}"
          docker buildx bake \
            --set "*.platform=linux/amd64,linux/arm64" \
            --set "*.output=type=registry" \
            php${PHP_VERSION//.}-slim-${{ matrix.variant }}
          PHP_PATCH_MINOR=`docker run --rm thecodingmachine/php:${PHP_VERSION}-v4-slim-cli php -v | head -n1 | grep -P '\d+\.\d+\.\d+' -o | head -n1` \
          docker buildx bake \
            --set "*.platform=linux/amd64,linux/arm64" \
            --set "*.output=type=registry" \
            php${PHP_VERSION//.}-${{ matrix.variant }}-all
          docker images --filter=reference=thecodingmachine/php >> $GITHUB_STEP_SUMMARY
